/*
 * Copyright (C) Contributors to the Suwayomi project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import { defineConfig } from '@lingui/cli';
// eslint-disable-next-line import/no-extraneous-dependencies
import { formatter } from '@lingui/format-po';

// eslint-disable-next-line import/no-default-export
export default defineConfig({
    sourceLocale: 'en',
    // !!!IMPORTANT!!!: 'locales' is auto-generated by tools/scripts/weblate/generatei18nResources.ts. Do not edit manually.
    locales: [
        'de',
        'en',
        'es',
        'fa',
        'fr',
        'hu',
        'it',
        'ja',
        'ko',
        'pl',
        'pt',
        'ru',
        'ta',
        'tr',
        'vi',
        'zh_Hans',
        'zh_Hant',
    ],
    catalogs: [
        {
            path: '<rootDir>/src/i18n/locales/{locale}',
            include: ['src'],
        },
    ],
    format: formatter({ lineNumbers: false }),
});
