name: CI Pull Request
on:
  pull_request:
jobs:
  build:
    name: ci-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJs
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11.1.2
          cache: true

      - run: pnpm setup

      - name: Install modules
        run: pnpm ci

      - name: Run ESLint
        run: pnpm lint

      - name: Run TSC
        run: pnpm tsc

      - name: Build app
        run: pnpm build
