name: Issue moderator

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: Moderate issues
        uses: tachiyomiorg/issue-moderator-action@v2
        with:
          repo-token: ${{ github.token }}
          duplicate-check-enabled: true
          existing-check-enabled: true
          auto-close-rules: |
            [
              {
                "type": "title",
                "regex": "^(?!(\[(Feature Request|Bug\] )))",
                "message": "Invalid title. Must start with either \"[Feature Request]\" or \"[Bug]\""
              },
              {
                "type": "title",
                "regex": ".*<short description>.*",
                "message": "You did not fill out the description in the title"
              },
              {
                "type": "title",
                "regex": ".*(<|>)+.*",
                "message": "You did not remove Angle brackets(< and >) from the title"
              },
              {
                "type": "title",
                "regex": "^\[(Feature Request|Bug)\](?!.{0,75}$)",
                "message": "The title is too long, keep it short and descriptive"
              },
              {
                "type": "title",
                "regex": "^\[(Feature Request|Bug)\](?!.{10,75}$)",
                "message": "The title is too short to provide any valuable short description"
              },
              {
                "type": "title",
                "regex": ".*\?.*)",
                "message": "The title is not supposed to be a question"
              },
              {
                "type": "body",
                "regex": "^(?!## (Device information|What feature should be added to Suwayomi\?))",
                "message": "The acknowledgment section was not removed"
              },
              {
                "type": "body",
                "regex": ".*(Suwayomi-WebUI version|Suwayomi-Server version|Server Operating System|Server Desktop Environment|Server JVM version|Client Operating System|Client Web Browser):.*(\\(Example:|<usually).*",
                "message": "The requested information was not filled out"
              },
              {
                "type": "body",
                "regex": ".*Remove this line after you are done.*",
                "message": "The lines requesting to be removed were not removed."
              }
            ]
